services:
  mongodb:
    image: mongo:8
    container_name: local_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: kids-camp-2026

volumes:
  mongo_data:
